baseURL: "https://zerainen.github.io/"
languageCode: "en-us"
title: "Alex Feldsinger"
theme: "toha"
params:
  background: "images/coding-background.jpg"
  logo:
    main: images/avatar.png
    inverted: images/avatar.png
    favicon: images/avatar.png
